server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: user_service
    password: user_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/jira

keycloak:
  server-url: http://keycloak:8080
  realm: jira
  client-id: jira-app
  client-secret: mu7oM7miPph6FrGZ1iEOyA6q7rUoYElF
  default-role: MEMBRE

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG